# Workflow description.
name: Terraform Provisioning

on:
  push:
    branches:
      - main

# Step definitions.
jobs:
  terraform:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    environment: staging
    
    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Validate Terraform
        run: terraform validate

      - name: Format code
        run: terraform fmt -check

      - name: Validate code
        id: check
        run: echo "Checks passed"

      - name: initialize Terraform
        if: success() && steps.check.outcome == 'success'
        run: terraform init

      - name: Terraform plan
        if: success() && steps.check.outcome == 'success'
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: success() && steps.check.outcome == 'success'
        run: terraform apply tfplan -auto-approve
        working-directory: terraform
